# Generated by Django 5.1.5 on 2025-01-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="tag",
            new_name="tags",
        ),
    ]
